require("dotenv").config();

const express = require("express");
const app = express();
 const connectionDB =  require("./config/db");
const authController = require('./controllers/authController');
const authRoutes = require('./routes/authRoutes');
const categoryRoutes = require('./routes/categoryRoutes');
const productRoutes = require('./routes/productRoutes');
const cartRoutes = require('./routes/cartRoutes');
const wishlistRoutes = require('./routes/wishlistRoutes');
const oderRoutes = require('./routes/orderRoutes');
const reviewRoutes = require('./routes/reviewRoutes');
const mongoose =  require('mongoose');
const PORT = process.env.PORT || 5000;
const path =  require('path');
connectionDB();
app.use(express.json());
app.use(express.urlencoded({extended :true}));
app.use('/uploads',express.static(path.join(__dirname,'uploads')));
app.use('/api/auth',authRoutes);
app.use('/api/categories', categoryRoutes);
app.use('/api/products',productRoutes); 
app.use('/api/cart',cartRoutes);
app.use('/api/wishlist',wishlistRoutes);
app.use('/api/orders',oderRoutes);
app.use('/api/products',reviewRoutes);
app.listen(PORT,"0.0.0.0", () => {
  console.log(`Server  running  at port : ${PORT}`);
});
